### ISSUE TITLE
Register/Login

### ISSUE THREAD

**Issue by aidarbn** [Tauka/uniquora-front#4]
No need in auto-login and auto-register. We need "Ok" button (which will confirm registering and login). 
Not working confirmation link on safari.

**Comment by kenzhemir** [comment]
I think the auto-login feature is pretty cool.

**Comment by Tauka** [comment]
@AidarBabanov Is there any explicit problems with auto-login you noticed? Or is it matter of UX design?

Thank you for reporting

**Comment by aidarbn** [comment]
First of all, when I register, probably I want to change my password, but I can't because it starts to register immediately after I typed last symbol. 

Secondly, I am using google chrome and I save my passwords. Web site doesn't auto-login with auto-filling, moreover I can't login by myself, because there is no any button. (Now it works, I don't know why it didn't work)

**Comment by Tauka** [comment]
> First of all, when I register, probably I want to change my password, but I can't because it starts to register immediately after I typed last symbol.

Therefore you have 2 input when registering, it's pretty hard to mistaken two times =)

> Secondly, I am using google chrome and I save my passwords. Web site doesn't auto-login with auto-filling, moreover I can't login by myself, because there is no any button. 

I was also testing this feature on MacOS Chrome and Windows 7 Chrome, and it worked. Let me know if you will have any problem with browser auto-fill in future
